// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHy-0lvvECx6S5p0BcjqZArtOFTLCo-4',
    appId: '1:774326429307:web:cbd9cb83c8438753a424de',
    messagingSenderId: '774326429307',
    projectId: 'greenbarnsolutions',
    authDomain: 'greenbarnsolutions.firebaseapp.com',
    storageBucket: 'greenbarnsolutions.appspot.com',
    measurementId: 'G-ZNZE5GPD9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKTVzFyI9M8cEJc3QG0Q5ghxtEXqXnbJw',
    appId: '1:774326429307:android:a3a00029741b104ba424de',
    messagingSenderId: '774326429307',
    projectId: 'greenbarnsolutions',
    storageBucket: 'greenbarnsolutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdupY5mDxp4uYd3X6ntPApgHYMBdDj44',
    appId: '1:774326429307:ios:5ff718f63ba0fce9a424de',
    messagingSenderId: '774326429307',
    projectId: 'greenbarnsolutions',
    storageBucket: 'greenbarnsolutions.appspot.com',
    iosBundleId: 'com.example.greenbarnsolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdupY5mDxp4uYd3X6ntPApgHYMBdDj44',
    appId: '1:774326429307:ios:4270344f55ec19f2a424de',
    messagingSenderId: '774326429307',
    projectId: 'greenbarnsolutions',
    storageBucket: 'greenbarnsolutions.appspot.com',
    iosBundleId: 'com.example.greenbarnsolutions.RunnerTests',
  );
}
